export const ACTIVE_USERS_REQUEST = 'ACTIVE_USERS_REQUEST'
export const ACTIVE_USERS_SUCCESS = 'ACTIVE_USERS_SUCCESS'
export const ACTIVE_USERS_FAIL = 'ACTIVE_USERS_FAIL'

export const ONLINE_PRACT_REQUEST = 'ONLINE_PRACT_REQUEST'
export const ONLINE_PRACT_SUCCESS= 'ONLINE_PRACT_SUCCESS'
export const ONLINE_PRACT_FAIL = 'ONLINE_PRACT_FAIL'

export const TOTAL_REQUESTS_REQUEST = 'TOTAL_REQUESTS_REQUEST'
export const TOTAL_REQUESTS_SUCCESS= 'TOTAL_REQUESTS_SUCCESS'
export const TOTAL_REQUESTS_FAIL = 'TOTAL_REQUESTS_FAIL'

export const COMPLETED_JOBS_REQUEST = 'COMPLETED_JOBS_REQUEST'
export const COMPLETED_JOBS_SUCCESS= 'COMPLETED_JOBS_SUCCESS'
export const COMPLETED_JOBS_FAIL = 'COMPLETED_JOBS_FAIL'


export const EMAIL_RESET = 'EMAIL_RESET'