export const EMAIL_LIST_REQUEST = 'EMAIL_LIST_REQUEST'
export const EMAIL_LIST_SUCCESS = 'EMAIL_LIST_SUCCESS'
export const EMAIL_LIST_FAIL = 'EMAIL_LIST_FAIL'
export const EMAIL_LIST_RESET = 'EMAIL_LIST_RESET'

export const EMAIL_CREATE_REQUEST = 'EMAIL_CREATE_REQUEST'
export const EMAIL_CREATE_SUCCESS= 'EMAIL_CREATE_SUCCESS'
export const EMAIL_CREATE_FAIL = 'EMAIL_CREATE_FAIL'

export const EMAIL_DETAILS_REQUEST = 'EMAIL_DETAILS_REQUEST'
export const EMAIL_DETAILS_SUCCESS= 'EMAIL_DETAILS_SUCCESS'
export const EMAIL_DETAILS_FAIL = 'EMAIL_DETAILS_FAIL'
export const EMAIL_DETAILS_RESET = 'EMAIL_DETAILS_RESET'

export const EMAIL_UPDATE_REQUEST = 'EMAIL_UPDATE_REQUEST'
export const EMAIL_UPDATE_SUCCESS= 'EMAIL_UPDATE_SUCCESS'
export const EMAIL_UPDATE_FAIL = 'EMAIL_UPDATE_FAIL'

export const EMAIL_DELETE_REQUEST = 'EMAIL_DELETE_REQUEST'
export const EMAIL_DELETE_SUCCESS = 'EMAIL_DELETE_SUCCESS'
export const EMAIL_DELETE_FAIL = 'EMAIL_DELETE_FAIL'
export const EMAIL_DELETE_RESET = 'EMAIL_DELETE_RESET'

export const EMAIL_RESET = 'EMAIL_RESET'