export const FIELD_LIST_REQUEST = 'FIELD_LIST_REQUEST'
export const FIELD_LIST_SUCCESS = 'FIELD_LIST_SUCCESS'
export const FIELD_LIST_FAIL = 'FIELD_LIST_FAIL'
export const FIELD_LIST_RESET = 'FIELD_LIST_RESET'

export const FIELD_CREATE_REQUEST = 'FIELD_CREATE_REQUEST'
export const FIELD_CREATE_SUCCESS= 'FIELD_CREATE_SUCCESS'
export const FIELD_CREATE_FAIL = 'FIELD_CREATE_FAIL'

export const FIELD_DETAILS_REQUEST = 'FIELD_DETAILS_REQUEST'
export const FIELD_DETAILS_SUCCESS= 'FIELD_DETAILS_SUCCESS'
export const FIELD_DETAILS_FAIL = 'FIELD_DETAILS_FAIL'

export const FIELD_UPDATE_REQUEST = 'FIELD_UPDATE_REQUEST'
export const FIELD_UPDATE_SUCCESS= 'FIELD_UPDATE_SUCCESS'
export const FIELD_UPDATE_FAIL = 'FIELD_UPDATE_FAIL'

export const FIELD_DELETE_REQUEST = 'FIELD_DELETE_REQUEST'
export const FIELD_DELETE_SUCCESS = 'FIELD_DELETE_SUCCESS'
export const FIELD_DELETE_FAIL = 'FIELD_DELETE_FAIL'
export const FIELD_DELETE_RESET = 'FIELD_DELETE_RESET'