export const PRACT_LIST_REQUEST = 'PRACT_LIST_REQUEST'
export const PRACT_LIST_SUCCESS = 'PRACT_LIST_SUCCESS'
export const PRACT_LIST_FAIL = 'PRACT_LIST_FAIL'
export const PRACT_LIST_RESET = 'PRACT_LIST_RESET'

export const PRACT_DELETE_REQUEST = 'PRACT_DELETE_REQUEST'
export const PRACT_DELETE_SUCCESS = 'PRACT_DELETE_SUCCESS'
export const PRACT_DELETE_FAIL = 'PRACT_DELETE_FAIL'
export const PRACT_DELETE_RESET = 'PRACT_DELETE_RESET'

export const PRACT_DETAILS_REQUEST = 'PRACT_DETAILS_REQUEST'
export const PRACT_DETAILS_SUCCESS= 'PRACT_DETAILS_SUCCESS'
export const PRACT_DETAILS_FAIL = 'PRACT_DETAILS_FAIL'
export const PRACT_DETAILS_RESET = 'PRACT_DETAILS_RESET'

export const PRACT_VERIFY_REQUEST = 'PRACT_VERIFY_REQUEST'
export const PRACT_VERIFY_SUCCESS= 'PRACT_VERIFY_SUCCESS'
export const PRACT_VERIFY_FAIL = 'PRACT_VERIFY_FAIL'
export const PRACT_VERIFY_RESET = 'PRACT_VERIFY_RESET'

export const PRACT_DEACTIVATE_REQUEST = 'PRACT_DEACTIVATE_REQUEST'
export const PRACT_DEACTIVATE_SUCCESS= 'PRACT_DEACTIVATE_SUCCESS'
export const PRACT_DEACTIVATE_FAIL = 'PRACT_DEACTIVATE_FAIL'
export const PRACT_DEACTIVATE_RESET = 'PRACT_DEACTIVATE_RESET'

export const PRACT_ACTIVATE_REQUEST = 'PRACT_ACTIVATE_REQUEST'
export const PRACT_ACTIVATE_SUCCESS= 'PRACT_ACTIVATE_SUCCESS'
export const PRACT_ACTIVATE_FAIL = 'PRACT_ACTIVATE_FAIL'
export const PRACT_ACTIVATE_RESET = 'PRACT_ACTIVATE_RESET'

export const PRACT_INVITE_REQUEST = 'PRACT_INVITE_REQUEST'
export const PRACT_INVITE_SUCCESS= 'PRACT_INVITE_SUCCESS'
export const PRACT_INVITE_FAIL = 'PRACT_INVITE_FAIL'
export const PRACT_INVITE_RESET = 'PRACT_INVITE_RESET'

export const PRACT_DECLINE_REQUEST = 'PRACT_DECLINE_REQUEST'
export const PRACT_DECLINE_SUCCESS= 'PRACT_DECLINE_SUCCESS'
export const PRACT_DECLINE_FAIL = 'PRACT_DECLINE_FAIL'
export const PRACT_DECLINE_RESET = 'PRACT_DECLINE_RESET'

export const PRACT_REJECT_REQUEST = 'PRACT_REJECT_REQUEST'
export const PRACT_REJECT_SUCCESS= 'PRACT_REJECT_SUCCESS'
export const PRACT_REJECT_FAIL = 'PRACT_REJECT_FAIL'

export const PRACT_EMAIL_REQUEST = 'PRACT_EMAIL_REQUEST'
export const PRACT_EMAIL_SUCCESS= 'PRACT_EMAIL_SUCCESS'
export const PRACT_EMAIL_FAIL = 'PRACT_EMAIL_FAIL'

export const PRACT_UPDATE_REQUEST = 'PRACT_UPDATE_REQUEST'
export const PRACT_UPDATE_SUCCESS= 'PRACT_UPDATE_SUCCESS'
export const PRACT_UPDATE_FAIL = 'PRACT_UPDATE_FAIL'

export const PRACT_RESET = 'PRACT_RESET'
